sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

before_install:
  - docker build -t test -f Dockerfile.test .
  - docker ps -a
  - docker run test /bin/sh -c "/etc/init.d/postgresql start; npm test;"

script:
  - npm test