install: true

sudo: required

language: node_js

services:
- docker

before_install:
- docker build -t test -f Dockerfile.test .

script:
- docker run test /bin/sh -c "/etc/init.d/postgresql start; npm test;"
