install: true

sudo: required

language: node_js

services:
- docker
- postgresql

addons:
  postgresql: "9.5"


before_install:
- psql -c 'create database test_db;' -U postgres
- docker build -t test -f Dockerfile.test .

script:
- docker run --net="host" -it -p 8080:8080 test /bin/sh -c "npm test"