sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t test -f Dockerfile.test .
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/test; bundle exec foreman start;"
  - docker ps -a
  - docker run test /bin/sh -c "/etc/init.d/postgresql start; npm test;"