#FROM debian:jessie
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get -y install sudo
RUN apt-get -y install curl

#install NodeJS and npm
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN apt-get -y install build-essential
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN npm install

COPY . /usr/src/app

EXPOSE 8080

#CMD [ "npm", "start" ]
